# Generated by Django 5.0.7 on 2025-09-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('word_training', '0002_load_initial_verbs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userword',
            new_name='word_traini_user_id_45cfdc_idx',
            old_name='word_traini_user_id_0f90ed_idx',
        ),
        migrations.RenameIndex(
            model_name='userword',
            new_name='word_traini_user_id_a3d01d_idx',
            old_name='word_traini_user_id_f2933c_idx',
        ),
    ]
