"""initial_schema

Revision ID: 1f460095e63c
Revises: 
Create Date: 2026-03-30 23:24:00.189600
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1f460095e63c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_definitions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('rarity', sa.Enum('COMMON', 'RARE', 'EPIC', 'LEGENDARY', name='badgerarity', native_enum=False), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_badge_definitions_metric_key'), 'badge_definitions', ['metric_key'], unique=False)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pronoun_set', sa.JSON(), nullable=False),
    sa.Column('tense_definitions', sa.JSON(), nullable=False),
    sa.Column('difficulty_tiers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('weekly_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Date(), nullable=False),
    sa.Column('ends_at', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_challenges_ends_at'), 'weekly_challenges', ['ends_at'], unique=False)
    op.create_index(op.f('ix_weekly_challenges_metric_key'), 'weekly_challenges', ['metric_key'], unique=False)
    op.create_index(op.f('ix_weekly_challenges_slug'), 'weekly_challenges', ['slug'], unique=True)
    op.create_index(op.f('ix_weekly_challenges_starts_at'), 'weekly_challenges', ['starts_at'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatrole', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('friend_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['friend_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'friend_user_id', name='uq_friend_link')
    )
    op.create_index(op.f('ix_friend_links_friend_user_id'), 'friend_links', ['friend_user_id'], unique=False)
    op.create_index(op.f('ix_friend_links_user_id'), 'friend_links', ['user_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('WORD_TRANSLATION', 'VERB_TRANSLATION', 'CONJUGATION', name='trainingmode', native_enum=False), nullable=False),
    sa.Column('language_pair', sa.String(length=16), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_active', 'training_sessions', ['user_id', 'mode', 'completed_at'], unique=False)
    op.create_index(op.f('ix_training_sessions_language_pair'), 'training_sessions', ['language_pair'], unique=False)
    op.create_index(op.f('ix_training_sessions_mode'), 'training_sessions', ['mode'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_code', sa.String(length=64), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['badge_code'], ['badge_definitions.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_code', name='uq_user_badge_slot')
    )
    op.create_index(op.f('ix_user_badges_badge_code'), 'user_badges', ['badge_code'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_challenge_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['weekly_challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_user_challenge_slot')
    )
    op.create_index(op.f('ix_user_challenge_progress_challenge_id'), 'user_challenge_progress', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_user_challenge_progress_user_id'), 'user_challenge_progress', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sound_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('theme_preference', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('WORD', 'VERB', 'CONJUGATION', name='progressitemtype', native_enum=False), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('language_pair', sa.String(length=16), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('unlocked', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_type', 'item_id', 'language_pair', name='uq_user_progress_slot')
    )
    op.create_index('idx_progress_probability', 'user_progress', ['user_id', 'item_type', 'language_pair', 'probability'], unique=False)
    op.create_index('idx_progress_unlock', 'user_progress', ['user_id', 'item_type', 'language_pair', 'unlocked'], unique=False)
    op.create_index(op.f('ix_user_progress_item_id'), 'user_progress', ['item_id'], unique=False)
    op.create_index(op.f('ix_user_progress_item_type'), 'user_progress', ['item_type'], unique=False)
    op.create_index(op.f('ix_user_progress_language_pair'), 'user_progress', ['language_pair'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('verbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('infinitive', sa.String(length=128), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('infinitive', 'language_id', name='uq_verbs_infinitive_language')
    )
    op.create_index(op.f('ix_verbs_infinitive'), 'verbs', ['infinitive'], unique=False)
    op.create_index(op.f('ix_verbs_language_id'), 'verbs', ['language_id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text', 'language_id', name='uq_words_text_language')
    )
    op.create_index(op.f('ix_words_language_id'), 'words', ['language_id'], unique=False)
    op.create_index(op.f('ix_words_text'), 'words', ['text'], unique=False)
    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_created_at'), 'xp_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_xp_events_reason'), 'xp_events', ['reason'], unique=False)
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    op.create_table('session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('WORD', 'VERB', 'CONJUGATION', name='progressitemtype', native_enum=False), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('multiplier_applied', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_items_item_id'), 'session_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_session_items_item_type'), 'session_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_session_items_session_id'), 'session_items', ['session_id'], unique=False)
    op.create_table('verb_conjugations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('mood', sa.String(length=64), nullable=False),
    sa.Column('tense', sa.String(length=128), nullable=False),
    sa.Column('pronoun', sa.String(length=32), nullable=False),
    sa.Column('conjugated_form', sa.String(length=128), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verb_id'], ['verbs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verb_id', 'language_id', 'mood', 'tense', 'pronoun', name='uq_verb_conjugation_slot')
    )
    op.create_index('idx_conjugations_lookup', 'verb_conjugations', ['verb_id', 'language_id', 'tense'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_language_id'), 'verb_conjugations', ['language_id'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_mood'), 'verb_conjugations', ['mood'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_pronoun'), 'verb_conjugations', ['pronoun'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_tense'), 'verb_conjugations', ['tense'], unique=False)
    op.create_index(op.f('ix_verb_conjugations_verb_id'), 'verb_conjugations', ['verb_id'], unique=False)
    op.create_table('verb_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('translation', sa.String(length=128), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verb_id'], ['verbs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verb_id', 'target_language_id', 'translation', name='uq_verb_translation')
    )
    op.create_index(op.f('ix_verb_translations_target_language_id'), 'verb_translations', ['target_language_id'], unique=False)
    op.create_index(op.f('ix_verb_translations_translation'), 'verb_translations', ['translation'], unique=False)
    op.create_index(op.f('ix_verb_translations_verb_id'), 'verb_translations', ['verb_id'], unique=False)
    op.create_table('word_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('target_language_id', sa.Integer(), nullable=False),
    sa.Column('translation', sa.String(length=128), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['target_language_id'], ['languages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'target_language_id', 'translation', name='uq_word_translation')
    )
    op.create_index(op.f('ix_word_translations_target_language_id'), 'word_translations', ['target_language_id'], unique=False)
    op.create_index(op.f('ix_word_translations_translation'), 'word_translations', ['translation'], unique=False)
    op.create_index(op.f('ix_word_translations_word_id'), 'word_translations', ['word_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_translations_word_id'), table_name='word_translations')
    op.drop_index(op.f('ix_word_translations_translation'), table_name='word_translations')
    op.drop_index(op.f('ix_word_translations_target_language_id'), table_name='word_translations')
    op.drop_table('word_translations')
    op.drop_index(op.f('ix_verb_translations_verb_id'), table_name='verb_translations')
    op.drop_index(op.f('ix_verb_translations_translation'), table_name='verb_translations')
    op.drop_index(op.f('ix_verb_translations_target_language_id'), table_name='verb_translations')
    op.drop_table('verb_translations')
    op.drop_index(op.f('ix_verb_conjugations_verb_id'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_tense'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_pronoun'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_mood'), table_name='verb_conjugations')
    op.drop_index(op.f('ix_verb_conjugations_language_id'), table_name='verb_conjugations')
    op.drop_index('idx_conjugations_lookup', table_name='verb_conjugations')
    op.drop_table('verb_conjugations')
    op.drop_index(op.f('ix_session_items_session_id'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_item_type'), table_name='session_items')
    op.drop_index(op.f('ix_session_items_item_id'), table_name='session_items')
    op.drop_table('session_items')
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_reason'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_created_at'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_words_text'), table_name='words')
    op.drop_index(op.f('ix_words_language_id'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_verbs_language_id'), table_name='verbs')
    op.drop_index(op.f('ix_verbs_infinitive'), table_name='verbs')
    op.drop_table('verbs')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_language_pair'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_item_type'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_item_id'), table_name='user_progress')
    op.drop_index('idx_progress_unlock', table_name='user_progress')
    op.drop_index('idx_progress_probability', table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_challenge_progress_user_id'), table_name='user_challenge_progress')
    op.drop_index(op.f('ix_user_challenge_progress_challenge_id'), table_name='user_challenge_progress')
    op.drop_table('user_challenge_progress')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_badge_code'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_mode'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_language_pair'), table_name='training_sessions')
    op.drop_index('idx_sessions_active', table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_friend_links_user_id'), table_name='friend_links')
    op.drop_index(op.f('ix_friend_links_friend_user_id'), table_name='friend_links')
    op.drop_table('friend_links')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_weekly_challenges_starts_at'), table_name='weekly_challenges')
    op.drop_index(op.f('ix_weekly_challenges_slug'), table_name='weekly_challenges')
    op.drop_index(op.f('ix_weekly_challenges_metric_key'), table_name='weekly_challenges')
    op.drop_index(op.f('ix_weekly_challenges_ends_at'), table_name='weekly_challenges')
    op.drop_table('weekly_challenges')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_badge_definitions_metric_key'), table_name='badge_definitions')
    op.drop_table('badge_definitions')
    # ### end Alembic commands ###
