# Generated by Django 5.2.5 on 2025-09-10 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=128, unique=True)),
                ('translation', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('probability', models.FloatField(default=1000)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_training.word')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'unlocked'], name='auto_traini_user_id_0f90ed_idx'), models.Index(fields=['user', 'word'], name='auto_traini_user_id_f2933c_idx')],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
