# Generated by Django 5.0.7 on 2025-09-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('verbs', '0002_load_initial_verbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConjugationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('FR', 'French'), ('ES', 'Spanish')], max_length=2)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('custom', 'Custom')], max_length=10)),
                ('fill_level', models.CharField(choices=[('easy', 'Easy (80% filled)'), ('medium', 'Medium (20% filled)'), ('hard', 'Hard (0% filled)')], max_length=10)),
                ('selected_tenses', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['language', 'difficulty_level'], name='verbs_conju_languag_8d9b53_idx'), models.Index(fields=['created_at'], name='verbs_conju_created_bf2517_idx'), models.Index(fields=['is_active'], name='verbs_conju_is_acti_5c86d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerbConjugation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('FR', 'French'), ('ES', 'Spanish')], max_length=2)),
                ('mood', models.CharField(max_length=50)),
                ('tense', models.CharField(max_length=50)),
                ('pronoun', models.CharField(blank=True, max_length=20)),
                ('conjugated_form', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjugations', to='verbs.verb')),
            ],
            options={
                'indexes': [models.Index(fields=['verb', 'language'], name='verbs_conju_verb_id_039b36_idx'), models.Index(fields=['verb', 'language', 'mood'], name='verbs_conju_verb_id_e1273d_idx'), models.Index(fields=['verb', 'language', 'mood', 'tense'], name='verbs_conju_verb_id_61fc9c_idx'), models.Index(fields=['language', 'mood', 'tense'], name='verbs_conju_languag_e6043b_idx')],
                'unique_together': {('verb', 'language', 'mood', 'tense', 'pronoun')},
            },
        ),
    ]
