# Generated by Django 5.2.5 on 2025-09-02 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=64, unique=True)),
                ('translation', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserVerb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked', models.BooleanField(default=False)),
                ('probability', models.FloatField(default=1000)),
                ('times_correct', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.verb')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'unlocked'], name='verbs_userv_user_id_b9b7ec_idx'), models.Index(fields=['user', 'verb'], name='verbs_userv_user_id_94bc10_idx')],
                'unique_together': {('user', 'verb')},
            },
        ),
    ]
