# Generated by Django 5.0.7 on 2025-09-26 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0002_load_initial_verbs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConjugation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('FR', 'French'), ('ES', 'Spanish')], max_length=2)),
                ('overall_score', models.FloatField(default=1000)),
                ('unlocked', models.BooleanField(default=False)),
                ('tense_scores', models.JSONField(default=dict)),
                ('total_attempts', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verbs.verb')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'language', 'unlocked'], name='verbs_userc_user_id_df22dc_idx'), models.Index(fields=['user', 'language', 'overall_score'], name='verbs_userc_user_id_31468e_idx'), models.Index(fields=['user', 'verb', 'language'], name='verbs_userc_user_id_cb844b_idx'), models.Index(fields=['last_practiced'], name='verbs_userc_last_pr_62f86a_idx')],
                'unique_together': {('user', 'verb', 'language')},
            },
        ),
    ]
