# Generated by Django 5.2.5 on 2025-08-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='fall-back.jpg', upload_to=''),
        ),
    ]
